project:
  type: website
  output-dir: docs

website:
  title: "Berufsschul-Digi-Teams"
  navbar:
    logo: "/logos/svlog.png"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "Auf dieser Seite:"

editor: visual

